config/routes.rb
Wikijuju::Application.routes.draw do
  get "collaborators/new"

  get "collaborators/create"

  get "users/show"

  get "subscriptions/new"

  get "wiki/create"

  devise_for :users

  get "index" => "welcome#index"

  get "about" => "welcome#about"

  root to: 'welcome#index'

  resources :wikis, only: [:new, :create, :show, :index] do
    resources :pages, only: [:new, :create, :show]
    resources :collaborators, only: [:new, :create]
  end

  resources :subscriptions, only: [:create]
  resources :users, only: [:show]

end

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base
  attr_accessible :wiki_id
  belongs_to :wiki
  belongs_to :user
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :body, :title, :wiki
  belongs_to :wiki
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body
  validates :name, presence: true

  has_many :wikis
  has_many :pages
  has_many :collaborations

  def public_wikis
    Wiki.users_public_wikis(id)
  end

  def private_wikis
    Wiki.users_private_wikis(id)
  end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]

  attr_accessible :name, :premium
  has_many :pages
  has_many :collaborations
  has_many :users, through: :collaborations
  belongs_to :user
  validates :name, presence: true, uniqueness: { case_sensitive: false }

  def self.all_public
    where(premium: false)
  end

  def self.users_public_wikis(user_id)
    where(user_id: user_id, premium: false)
  end

  def self.users_private_wikis(user_id)
    where(user_id: user_id, premium: true)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def user_not_authorized
    flash[:error] = "You are not authorized to perform this action."
    redirect_to root_path
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user
      @wiki = Wiki.find(params[:wiki_id])
      if @user.collaborations.where(wiki_id: @wiki.id).present?
        flash.now[:error] = "That user is already a collaborator on this JuJu."
        render :new
      else
        @user.collaborations.create(wiki_id: @wiki.id)
        flash[:notice] = "Collaboration created successfully."
        redirect_to wiki_path(@wiki)
      end
    else
      flash.now[:error] = "No user with that email address could be found."
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def new
    @page = Page.new
    @wiki = Wiki.find(params[:wiki_id])
  end

  def create
    @page = Page.new(params[:page])
    @wiki = Wiki.find(params[:wiki_id])
    @page.user_id = current_user.id
    @page.wiki = @wiki
    if @page.save
      flash[:notice] = "Your page was saved."
      redirect_to [@wiki, @page]
    else
      flash.now[:error] = "There was an error saving your page."
      render :new
    end
  end

  def show
    @wiki = Wiki.find(params[:wiki_id])
    @page = Page.find(params[:id])
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def create
    customer = Stripe::Customer.create(
      :card => params[:stripeToken],
      :plan => "wikijuju_premium",
      :email => current_user.email
    )

    current_user.stripe_id = customer.id 
    current_user.premium = true
    current_user.save

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  before_filter :authenticate_user!, only: [:create, :new]

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new(params[:wiki])
    @wiki.user = current_user
    if @wiki.save
      flash[:notice] = "Your JuJu was saved."
      redirect_to @wiki
    else
      flash.now[:error] = "There was an error saving your JuJu."
      render :new
    end
  end

  def show
    @wiki = Wiki.find(params[:id])
    authenticate_user! if @wiki.premium
    authorize @wiki
    @pages = @wiki.pages
    if request.path != wiki_path(@wiki)
      redirect_to @wiki, status: :moved_permanently
    end
  end

  def index
    @wikis = Wiki.all_public
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wiki_helper.rb
module WikiHelper
end

app/views/collaborators/create.html.erb
<h1>Collaborators#create</h1>
<p>Find me in app/views/collaborators/create.html.erb</p>

app/views/collaborators/new.html.erb
<%= form_tag(wiki_collaborators_path) do %>
  <%= label_tag(:email, "Collaborator Email:") %>
  <%= email_field_tag(:email) %>
  <%= submit_tag("Add") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wikijuju</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "WikiJuJu", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Wikis", wikis_path %></li>
      <div class="pull-right user-info">
        <% if current_user %>
          Hello <%= link_to current_user.name, current_user %>!
          <%= link_to edit_user_registration_path, class: 'btn btn-mini' do %>
             <i class="icon-user"> </i>
          <% end %>
          <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-mini' do %>
            <i class="icon-share-alt"> </i>
          <% end %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path %> or 
          <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>
    </ul>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

<%= yield %>

</body>
</html>

app/views/pages/_page.html.erb
<p><%= link_to page.title, [wiki, page] %></p>

app/views/pages/new.html.erb
<%= form_for [@wiki, @page], html: { class: 'form-horizontal' } do |f| %>
  <%= f.error_messages %>

  <div class="control-group">
    <%= f.label :title, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :title %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :body, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :body %>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <%= f.submit "Create", class: 'btn' %>
    </div>
  </div>

<% end %>

app/views/pages/show.html.erb
<h1><%= link_to @wiki.name, @wiki %> > <%= @page.title %></h1>
<p><%= @page.body %></p>

app/views/subscriptions/_form.html.erb
<%= form_tag subscriptions_path do %>

  <script src="https://checkout.stripe.com/checkout.js" 
    class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-description="Subscribe to create private JuJus"
    data-amount="500"
    data-email="<%= current_user.email %>" 
    data-label="Upgrade to Premium"
    data-panel-label="Subscribe for {{amount}}/mo" >
  </script>

<% end %>

app/views/subscriptions/create.html.erb
<h2>Thanks, you subscribed for <strong>$5.00</strong> per month.</h2>

app/views/users/show.html.erb
<h1><%= "#{@user.name}'s Profile" %></h1>

<div>
  <%= link_to "Create a JuJu", new_wiki_path, class: 'btn btn-primary btn-medium' %>
</div>

<h3>Public JuJus</h3>

<%= render partial: "wikis/wiki", collection: @user.public_wikis %>

<h3>Private JuJus</h3>
<% if @user.premium; %>
  <%= render partial: "wikis/wiki", collection: @user.private_wikis %>
<% else %>
  <%= render partial: "subscriptions/form" %>
<% end %>

app/views/welcome/about.html.erb
<h1>About WikiJuJu</h1>
<p>Wiki JuJu is where you can go for all of your JuJu information. This is a wiki all about the JuJu.</p>

app/views/welcome/index.html.erb
<div class="hero-unit">
  <h1>WikiJuJu</h1>
  <p>WikiJuJu is for all things JuJu</p>

  <p>
    <%= link_to "Create a JuJu", new_wiki_path, class: 'btn btn-primary btn-large' %>

    <% if current_user && !current_user.premium %>
      <%= render partial: "subscriptions/form" %>
    <% end %>

  </p>

</div>

<div class="row">
  <div class="span4">
    <h2>This...</h2>
    <p> </p>
  </div>
  <div class="span4">
    <h2>IS...</h2>
    <p> </p>
  </div>
  <div class="span4">
    <h2>WikiJuJu!</h2>
    <p> </p>
  </div>
</div>

app/views/wikis/_wiki.html.erb
<p><%= link_to wiki.name, wiki %></p>

app/views/wikis/index.html.erb
<%= render partial: 'wiki', collection: @wikis %>

app/views/wikis/new.html.erb
<%= form_for @wiki do |f| %>
  <%= f.error_messages %>

  <div class="control-group">
    <%= f.label :name, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>

  <% if current_user.premium %>
    <div class="checkbox">
      <%= f.label :premium do %>
        <%= f.check_box :premium %> Private JuJu
      <% end %>
    </div>
  <% end %>

  <div class="control-group">
    <div class="controls">
      <%= f.submit "Create", class: 'btn' %>
    </div>
  </div>

<% end %>

app/views/wikis/show.html.erb
<h1><%= @wiki.name %></h1>

<%= render partial: 'pages/page', collection: @pages, locals: { wiki: @wiki } %>

<p>
  <%= link_to "Create a New Page", new_wiki_page_path(wiki_id: @wiki.id), class: 'btn btn-primary btn-medium' %>

  <%= link_to "Add Collaborator", new_wiki_collaborator_path(wiki_id: @wiki.id), class: 'btn btn-primary btn-medium' if current_user.premium %>
</p>